---
- name: Configuring Prod Environment to use repository from Apache web server
  hosts: prod
  become: yes
  vars:
    Apache_hostname: "ApacheWebServer"
  tasks:
  - name: Append offical repo URl to /etc/apt/sources.list file
      blockinfile:
        path: /etc/apt/sources.list
        block: |
          deb [trusted=yes] http://{{ ip_result.json.origin }}/test-repo/ ./
        insertafter: "main"
  - name: Obtain public IP of Apache WEB SERVER
      uri:
        url: https://httpbin.org/ip
        return_content: yes
      delegate_to: "{{ Apache_hostname }}"
      register: ip_result

  - name: Update apt Cache
      apt:
        update_cache: yes

    - name: Loop through list to show apt cache policy for each service
      ansible.builtin.shell: apt-cache policy {{ item }}
      loop:
        - docker
        - nginx
        - apache2
        - cowsay
        - htop
      register: apt_policy_output

    - name: Print apt cache policy outputs
      debug:
        var: apt_policy_output
