---
- name: Configuring Test Environment to use repository from Apache web server
  hosts: test
  become: yes
  vars:
    Apache_hostname: "Apache"
  tasks:
    - name: Create test.list file
      file:
        path: "/etc/apt/sources.list.d/test.list"
        state: touch

    - name: Obtain public IP of Apache WEB SERVER
      uri:
        url: https://httpbin.org/ip
        return_content: yes
      delegate_to: {{ Apache_hostname }}
      register: ip_result

    - name: Edit test.list file inside /etc/apt/sources.list.d/ directory
      copy:
        dest: "/etc/apt/sources.list.d/test.list"
        content: |
          deb [trusted=yes] http://{{ ip_result.json.origin }}/test-repo/ ./

    - name: Update apt Cache
      apt:
        update_cache: yes

    - name: Loop through list to show apt cache policy for each service
      ansible.builtin.shell: apt-cache policy {{ item }}
      loop:
        - docker
        - nginx
        - apache2
        - cowsay
        - htop
      register: apt_policy_output

    - name: Print apt cache policy outputs
      debug:
        var: apt_policy_output
